import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '@/contexts/auth.context';
import SideNav from "@/components/SideNav";

const inter = Inter({
  variable: '--font-inter',
  subsets: ["latin"],
})

const geistInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <>
            <p>!!!</p>
            {children}
            <SideNav />
          </>
        </AuthProvider>
      </body>
    </html>
  );
}
